okx/exchain-go-sdk

README.md, client/query_test.go, client/transact_test.go, go.sum, sample/main.go
add an sample for user to start a journey on OKChain by Golang
=> add sample to gosdk

client_test.go, mocks/mock_client.go, module/auth/query_test.go, module/dex/query_test.go
=> FINISH: dex query products ut

client.go, client_test.go, mocks/mock_client.go, mocks/mock_response.go, module/auth/query_test.go, module/dex/query_test.go, module/dex/tx_test.go
=> FINISH: dex tx ut

client_test.go, mocks/mock_client.go, module/dex/offine_test.go, module/dex/query_test.go, module/dex/tx_test.go
=> FINISH: dex offline txs ut 

module/dex/offine_test.go, module/dex/tx_test.go
=> FINISH: all queries and txs ut in module dex 

.circleci/config.yml, mocks/mock_client.go, sample/main.go, types/params/params.go
=> recover ut in circileCI

client_test.go
=> FIX: succeed ut

client_test.go, mocks/mock_client.go, module/order/query_test.go
=> FINISH: all queries ut in module order

module/auth/query_test.go, module/base_client.go, module/dex/offine_test.go, module/dex/query_test.go, module/dex/tx_test.go, module/order/query_test.go, module/order/tx_test.go, types/client.go
=> OPTIMIZE: add Gas into fee payer

module/order/query_test.go, sample/main.go
=> FIX: sample

client_test.go, module/auth/query_test.go, module/dex/offine_test.go, module/dex/offline.go, module/dex/query_test.go, module/dex/tx_test.go, module/order/query_test.go, module/order/tx.go, module/order/tx_test.go
=> FINISH: all txs ut in order module

client_test.go, mocks/mock_client.go, module/token/query.go, module/token/query_test.go, module/token/types/types.go
=> FINISH: all queries ut in module token

client_test.go, module/token/query_test.go, module/token/tx_test.go, types/params/check.go
=> FINISH: all txs ut in token module

client_test.go, module/slashing/tx_test.go, module/token/query_test.go
=> FINISH: all txs ut in slashing module

client_test.go, mocks/mock_client.go, module/staking/query_test.go, types/codec.go
=> FINISH: all queries ut in staking module

client_test.go, mocks/mock_client.go, module/dex/offine_test.go, module/dex/tx_test.go, module/order/tx_test.go, module/slashing/tx_test.go, module/staking/tx_test.go, module/tendermint/query_test.go, module/token/tx_test.go
=> FINISH: all txs ut in staking module

exposed/backend.go, mocks/mock_client.go, module/backend/query.go, module/backend/query_test.go, module/backend/types/types.go, types/params/check.go, types/params/params.go
=> FINISH: all queries ut in backend module

module/auth/query_test.go, module/backend/query_test.go, module/dex/offine_test.go, module/dex/query_test.go, module/order/query_test.go, module/staking/query_test.go, module/staking/tx_test.go, module/token/query_test.go, module/token/tx_test.go
=> OPTIMIZE: promote ut coverage of module 

module/dex/tx_test.go, module/token/query_test.go, types/params/check.go, utils/account_test.go, utils/errors_test.go, utils/order_test.go
=>  OPTIMIZE: promote ut coverage utils/account

utils/order.go, utils/order_test.go, utils/utils_test.go
=> OPTIMIZE: TestParseValAddresses ut

README.md, mocks/mock_client.go, module/slashing/types/msg.go, utils/account_test.go, utils/backend.go, utils/backend_test.go, utils/tendermint_test.go, utils/token_test.go, utils/utils_test.go
=> FINISH: raise the ut coverage of the whole project

README.md
=> FIX:README.md

sample/main.go, types/std_tx.go
=> FIX: recover 'Fee' in StdSignDoc

client.go, exposed/distribution.go, module/distribution/alias.go, module/distribution/distribution.go, module/distribution/tx.go, module/distribution/types/msg.go, module/distribution/types/types.go, sample/main.go, types/std_tx.go
=> FINISH: tx functions in distr

module/token/tx.go, module/token/types/msg.go, module/token/types/types.go, types/params/check.go
=> add token tx about mint & burn

module/distribution/tx_test.go, module/staking/query_test.go, module/token/tx_test.go
=> FINISH: mint && burn ut in token module

exposed/governance.go, module/governance/tx.go, module/governance/tx_test.go, module/governance/types/types.go, module/governance/utils.go
=> FINISH: SubmitDelistProposal function in gov module

exposed/governance.go, module/governance/tx.go, module/governance/tx_test.go, module/governance/types/types.go, module/governance/utils.go
=> FINISH: SubmitCommunityPoolSpendProposal function in gov module

exposed/governance.go, module/governance/tx.go, module/governance/tx_test.go, module/governance/types/msg.go, module/governance/types/types.go, types/params/check.go
=> FINISH: Deposit function in gov module

alias.go, exposed/governance.go, module/governance/tx.go, module/governance/tx_test.go, module/governance/types/msg.go, module/governance/types/types.go, module/governance/utils.go, types/params/check.go
=> FINISH: Vote function in gov module

alias.go, exposed/governance.go, mocks/mock_client.go, module/governance/alias.go, module/governance/query.go, module/governance/query_test.go, module/governance/tx_test.go, module/governance/types/types.go, module/token/query_test.go, types/params/params.go
=> FINISH: query proposals function in gov module

module/governance/query.go, module/governance/query_test.go
=> FIX: bug in query proposals function

exposed/staking.go, module/staking/tx.go, module/staking/tx_test.go, module/staking/types/msg.go, module/staking/types/types.go, sample/main.go, types/params/check.go
=> FIX: fit the gosdk to the latest staking msgs in OKChain

exposed/dex.go, module/dex/tx.go, module/dex/tx_test.go, module/dex/types/msg.go, module/dex/types/types.go
=> FINISH: Register DEX Operator tx in dex module

exposed/dex.go, module/dex/tx.go, module/dex/tx_test.go, module/dex/types/msg.go, module/dex/types/types.go
=> FINISH: Edit DEX Operator tx in dex module

go.mod
=> fix ci issue

go.mod, go.sum
=> FIX: update go.mod to the latest OKExChain dev

README.md
=> FINISH: update Readme

README.md
=> FIX: Readme

alias.go
=> OPTIMIZE: update gosdk alias

module/base_client.go
=> FIX: fits CalculateGas

client.go, exposed/evm.go, go.sum, module/evm/evm.go, module/evm/tx.go, module/evm/types/types.go, utils/evm.go
=> FINISH: txs in evm module

mocks/mock_client.go, module/evm/query.go, module/evm/query_test.go, module/evm/tx_test.go, module/staking/tx_test.go
=> FINISH: ut of evm txs

utils/account_test.go, utils/evm_test.go
=> FINISH: ToCosmosAddress ut in utils

utils/evm_test.go
=> FINISH: payload builder ut

utils/evm.go
=> FINISH: get eth addr from cosmos addr

alias.go, exposed/evm.go, module/evm/query.go, module/evm/types/types.go
=> FINISH: query code in evm module

mocks/mock_client.go, module/evm/query_test.go
=> FINISH: query code ut in evm module

module/evm/tx_test.go, module/tendermint/query_test.go
=> OPTIMIZE: enhance ut coverage

module/evm/tx.go, module/evm/tx_test.go
=> FIX: fit the precision of evm tx with latest OKExChain

alias.go, exposed/evm.go, module/evm/query.go, module/evm/types/types.go, utils/evm.go
=> FINISH: query storage at xxx in evm

mocks/mock_client.go, module/evm/query_test.go
=> FINISH: query storage at xxx ut in evm

module/evm/tx.go, module/evm/tx_test.go
=> FIX: empty amount str in send tx of evm module

utils/account.go
=> FINISH: add reminder in GenerateMnemonic

exposed/farm.go, module/farm/query.go, module/farm/types/types.go
=> add querying earning in farm

exposed/evm.go, go.mod, go.sum, module/evm/utils.go, module/evm/utils_test.go
=> add GetTxHash() in evm module

exposed/tendermint.go, module/evm/utils.go, module/evm/utils_test.go, module/tendermint/query.go, types/client.go, types/mock_client.go
=> add functions to query status

sample/ethclient/ethclient.go
=> modify the receipt

README.md
=> Update api more details link

sample/client/main.go, sample/feesplit/main.go
=> remove mnemonic
